site_name: hmcdj
site_description: "documentation for hmcdj"
repo_url: "https://github.com/telos-collaboration/hmcdj"
repo_name: "telos-collaboration/hmcdj"
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

plugins:
  - search
  - literate-nav
  - repo-docs:
      root_files:
        - CONTRIBUTING.md
        - CODE_OF_CONDUCT.md

nav:
  - Introduction: intro.md
  - Usage:
    - Installing: installing.md
    - Running: running.md
  - Development:
    - Writing new decks: newdecks.md
    - Guide to contributing: _repo/CONTRIBUTING.md
    - Code of conduct: _repo/CODE_OF_CONDUCT.md

theme: readthedocs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
